#!/bin/csh

source /vol/eecs392/env/questasim.env

mkdir -p lib
make -f Makefile.questa dpi_lib32 LIBDIR=lib
 
# vsim -c -do functions_sim.do

# vsim -c -do fir_sim.do

vsim -c -do fir_cmplx_sim.do

# vsim -c -do iir_sim.do
