set paths_array(TS,10) {}
set paths_array(TS,11) {}
set paths_array(TS,12) {}
set paths_array(start_clock,1) {fm_radio|clock:rising}
set paths_array(TS,13) {}
set paths_array(start_clock,2) {fm_radio|clock:rising}
set paths_array(TS,14) {}
set paths_array(start_clock,3) {fm_radio|clock:rising}
set paths_array(TS,15) {}
set paths_array(start_clock,4) {System:rising}
set paths_array(TS,16) {-Timing constraint applied as multi cycle path with factor 2 (from c:square_32s|state_derived_clock[0] to c:square_32s|state_derived_clock[0])}
set paths_array(start_clock,5) {fm_radio|clock:rising}
set paths_array(TS,17) {-Timing constraint applied as multi cycle path with factor 2 (from c:gain_32s_10s_1|state_derived_clock[0] to c:gain_32s_10s_1|state_derived_clock[0])}
set paths_array(start_clock,6) {System:rising}
set paths_array(TS,18) {-Timing constraint applied as multi cycle path with factor 2 (from c:gain_32s_10s_0|state_derived_clock[0] to c:gain_32s_10s_0|state_derived_clock[0])}
set paths_array(start_clock,7) {fm_radio|clock:rising}
set paths_array(start_clock,8) {gain_32s_10s_1|state_derived_clock[0]:rising}
set paths_array(start_clock,9) {gain_32s_10s_0|state_derived_clock[0]:rising}
set paths_array(s_line,1) {0}
set paths_array(s_line,2) {0}
set paths_array(s_line,3) {0}
set paths_array(s_line,4) {0}
set paths_array(slack,1) {-0.807}
set paths_array(s_line,5) {0}
set paths_array(slack,2) {0.949}
set paths_array(s_line,6) {0}
set paths_array(slack,3) {0.949}
set paths_array(s_line,7) {0}
set paths_array(slack,4) {2.862}
set paths_array(s_line,8) {0}
set paths_array(slack,5) {3.492}
set paths_array(s_line,9) {0}
set paths_array(slack,6) {4.431}
set paths_array(slack,7) {4.646}
set paths_array(slack,8) {5.034}
set paths_array(pro_slack,1) {0}
set paths_array(slack,9) {5.315}
set paths_array(pro_slack,2) {0}
set paths_array(start_type,1) {reg}
set paths_array(start_type,2) {reg}
set paths_array(pro_slack,3) {0}
set paths_array(start_type,3) {reg}
set paths_array(pro_slack,4) {0}
set paths_array(skew,10) {0.0}
set paths_array(start_type,4) {reg}
set paths_array(pro_slack,5) {0}
set paths_array(skew,11) {0.0}
set paths_array(start_type,5) {reg}
set paths_array(pro_slack,6) {0}
set paths_array(skew,12) {0.0}
set paths_array(start_type,6) {reg}
set paths_array(pro_slack,7) {0}
set paths_array(skew,13) {0.0}
set paths_array(start_type,7) {reg}
set paths_array(pro_slack,8) {0}
set paths_array(skew,14) {0.0}
set paths_array(pro_slack,10) {0}
set paths_array(start_type,8) {reg}
set paths_array(pro_slack,9) {0}
set paths_array(skew,15) {0.0}
set paths_array(pro_slack,11) {0}
set paths_array(start_type,9) {reg}
set paths_array(skew,16) {0.0}
set paths_array(pro_slack,12) {0}
set paths_array(skew,17) {0.0}
set paths_array(pro_slack,13) {0}
set paths_array(skew,18) {0.0}
set paths_array(pro_slack,14) {0}
set paths_array(pro_slack,15) {0}
set paths_array(pro_slack,16) {0}
set paths_array(e_line,10) {0}
set paths_array(pro_slack,17) {0}
set paths_array(e_line,11) {0}
set paths_array(pro_slack,18) {0}
set paths_array(e_line,12) {0}
set paths_array(e_line,13) {0}
set paths_array(start_type,10) {reg}
set paths_array(e_line,14) {0}
set paths_array(start_type,11) {reg}
set paths_array(end_clk_dly,10) {0.000}
set paths_array(e_line,15) {0}
set paths_array(start_type,12) {reg}
set paths_array(end_clk_dly,11) {0.000}
set paths_array(e_line,16) {0}
set paths_array(start_type,13) {reg}
set paths_array(end_clk_dly,12) {0.000}
set paths_array(e_line,17) {0}
set paths_array(start_type,14) {reg}
set paths_array(end_clk_dly,13) {0.000}
set paths_array(e_line,18) {0}
set paths_array(start_type,15) {reg}
set paths_array(end_clk_dly,14) {0.000}
set paths_array(start_type,16) {reg}
set paths_array(end_clk_dly,15) {0.000}
set paths_array(start_type,17) {reg}
set paths_array(end_clk_dly,16) {0.000}
set paths_array(start_type,18) {reg}
set paths_array(end_clk_dly,17) {0.000}
set paths_array(TS,1) {}
set paths_array(end_clk_dly,18) {0.000}
set paths_array(TS,2) {}
set paths_array(TS,3) {}
set paths_array(skew,1) {0.0}
set paths_array(TS,4) {}
set paths_array(skew,2) {0.0}
set paths_array(TS,5) {}
set paths_array(skew,3) {0.0}
set paths_array(TS,6) {}
set paths_array(skew,4) {0.0}
set paths_array(TS,7) {}
set paths_array(skew,5) {0.0}
set paths_array(TS,8) {}
set paths_array(skew,6) {0.0}
set paths_array(TS,9) {}
set paths_array(skew,7) {0.0}
set paths_array(skew,8) {0.0}
set paths_array(skew,9) {0.0}
set paths_array(index,10) {10}
set paths_array(index,11) {11}
set paths_array(index,12) {12}
set paths_array(index,13) {13}
set paths_array(index,14) {14}
set paths_array(index,15) {15}
set paths_array(index,16) {16}
set paths_array(index,17) {17}
set paths_array(index,18) {18}
set paths_array(end_point,1) {fir_cmplx_inst/real_product_ret[28]}
set paths_array(data_delay,1) {0}
set paths_array(data_delay,2) {0}
set paths_array(end_point,2) {left_gain_inst/dout[24]}
set paths_array(end_point,3) {right_gain_inst/dout[24]}
set paths_array(data_delay,3) {0}
set paths_array(end_point,4) {demodulate_inst/qarctan_inst/divisor[31]}
set paths_array(data_delay,4) {0}
set paths_array(end_point,5) {mult_demod_lmr_inst/dout[20]}
set paths_array(data_delay,5) {0}
set paths_array(end_point,6) {demodulate_inst/qarctan_inst/data_out_temp[24]}
set paths_array(data_delay,6) {0}
set paths_array(end_point,7) {square_bp_pilot_inst/dout[20]}
set paths_array(data_delay,7) {0}
set paths_array(end_point,8) {left_deemph_inst/state_ret}
set paths_array(data_delay,8) {0}
set paths_array(end_clk_dly,1) {0.000}
set paths_array(end_point,9) {right_deemph_inst/state_ret}
set paths_array(data_delay,9) {0}
set paths_array(end_clk_dly,2) {0.000}
set paths_array(status_msg,10) {}
set paths_array(end_clock,10) {div_32s_32s|state_derived_clock[5]:rising}
set paths_array(end_clk_dly,3) {0.000}
set paths_array(status_msg,11) {}
set paths_array(end_clock,11) {fm_radio|clock:rising}
set paths_array(end_clk_dly,4) {0.000}
set paths_array(status_msg,12) {}
set paths_array(end_clock,12) {add|state_derived_clock:rising}
set paths_array(end_clk_dly,5) {0.000}
set paths_array(status_msg,13) {}
set paths_array(end_clock,13) {div_32s_32s|state_derived_clock[5]:rising}
set paths_array(end_clk_dly,6) {0.000}
set paths_array(status_msg,14) {}
set paths_array(end_clock,14) {fm_radio|clock:rising}
set paths_array(end_clk_dly,7) {0.000}
set paths_array(status_msg,15) {}
set paths_array(end_clock,15) {fm_radio|clock:rising}
set paths_array(end_clk_dly,8) {0.000}
set paths_array(status_msg,16) {}
set paths_array(end_clock,16) {square_32s|state_derived_clock[0]:rising}
set paths_array(end_clk_dly,9) {0.000}
set paths_array(status_msg,17) {}
set paths_array(end_clock,17) {gain_32s_10s_1|state_derived_clock[0]:rising}
set paths_array(status_msg,18) {}
set paths_array(end_clock,18) {gain_32s_10s_0|state_derived_clock[0]:rising}
set paths_array(start_clock,10) {fm_radio|clock:rising}
set paths_array(start_clock,11) {div_32s_32s|state_derived_clock[5]:rising}
set paths_array(start_clock,12) {fm_radio|clock:rising}
set paths_array(start_clock,13) {System:rising}
set paths_array(start_clock,14) {square_32s|state_derived_clock[0]:rising}
set paths_array(start_clock,15) {add|state_derived_clock:rising}
set paths_array(margin,1) {0}
set paths_array(start_clock,16) {square_32s|state_derived_clock[0]:rising}
set paths_array(margin,2) {0}
set paths_array(start_clock,17) {gain_32s_10s_1|state_derived_clock[0]:rising}
set paths_array(margin,3) {0}
set paths_array(start_clock,18) {gain_32s_10s_0|state_derived_clock[0]:rising}
set paths_array(margin,4) {0}
set paths_array(margin,5) {0}
set paths_array(margin,6) {0}
set paths_array(e_line,1) {0}
set paths_array(margin,7) {0}
set paths_array(e_line,2) {0}
set paths_array(margin,8) {0}
set paths_array(e_line,3) {0}
set paths_array(margin,9) {0}
set paths_array(e_line,4) {0}
set paths_array(e_line,5) {0}
set paths_array(e_line,6) {0}
set paths_array(e_line,7) {0}
set paths_array(e_line,8) {0}
set paths_array(e_line,9) {0}
set paths_array(sig) {/home/mwp8699/CE387-Assignments/final_project/syn/fm_radio.prj|rev_1 {} /home/mwp8699/CE387-Assignments/final_project/syn/rev_1/sdc_verif_slack.itd correlate 1 slack 1 {} {} {} {} {} {} 0 1 0 1 1}
set paths_array(req_time,10) {10.0}
set paths_array(req_time,11) {10.0}
set paths_array(req_time,12) {10.0}
set paths_array(passed,1) {0}
set paths_array(req_time,13) {10.0}
set paths_array(passed,2) {0}
set paths_array(req_time,14) {10.0}
set paths_array(passed,3) {0}
set paths_array(req_time,15) {10.0}
set paths_array(passed,4) {0}
set paths_array(req_time,16) {20.0}
set paths_array(margin_msg,1) {}
set paths_array(passed,5) {0}
set paths_array(req_time,17) {20.0}
set paths_array(margin_msg,2) {}
set paths_array(passed,6) {0}
set paths_array(req_time,18) {20.0}
set paths_array(margin_msg,3) {}
set paths_array(passed,7) {0}
set paths_array(margin_msg,4) {}
set paths_array(passed,8) {0}
set paths_array(margin_msg,5) {}
set paths_array(passed,9) {0}
set paths_array(margin_msg,6) {}
set paths_array(margin_msg,7) {}
set paths_array(margin_msg,8) {}
set paths_array(margin_msg,9) {}
set paths_array(passed,10) {0}
set paths_array(passed,11) {0}
set paths_array(passed,12) {0}
set paths_array(passed,13) {0}
set paths_array(passed,14) {0}
set paths_array(passed,15) {0}
set paths_array(passed,16) {0}
set paths_array(passed,17) {0}
set paths_array(passed,18) {0}
set paths_array(start_point,1) {fir_cmplx_inst/realshift_reg_CR31}
set paths_array(start_point,2) {left_gain_inst/DEQUANTIZE_27\.i_56_ml_ml_muladd_0[28:0]}
set paths_array(start_point,3) {right_gain_inst/DEQUANTIZE_27\.i_56_ml_ml_muladd_0[28:0]}
set paths_array(start_point,4) {demodulate_inst/qarctan_imag[23]}
set paths_array(start_point,5) {mult_demod_lmr_inst/calc_ret_0[0]}
set paths_array(start_point,6) {demodulate_inst/qarctan_real[23]}
set paths_array(start_point,7) {square_bp_pilot_inst/calc_ret_31[0]}
set paths_array(start_point,8) {left_gain_inst/in_rd_en_1}
set paths_array(start_point,9) {right_gain_inst/in_rd_en_1}
set paths_array(index,1) {1}
set paths_array(index,2) {2}
set paths_array(status_msg,1) {}
set paths_array(end_clock,1) {fm_radio|clock:rising}
set paths_array(index,3) {3}
set paths_array(status_msg,2) {}
set paths_array(end_clock,2) {gain_32s_10s_1|state_derived_clock[0]:rising}
set paths_array(index,4) {4}
set paths_array(end_clock,3) {gain_32s_10s_0|state_derived_clock[0]:rising}
set paths_array(status_msg,3) {}
set paths_array(index,5) {5}
set paths_array(end_clock,4) {System:rising}
set paths_array(status_msg,4) {}
set paths_array(index,6) {6}
set paths_array(req_time,1) {10.0}
set paths_array(end_clock,5) {System:rising}
set paths_array(status_msg,5) {}
set paths_array(index,7) {7}
set paths_array(req_time,2) {10.0}
set paths_array(end_clock,6) {fm_radio|clock:rising}
set paths_array(status_msg,6) {}
set paths_array(index,8) {8}
set paths_array(req_time,3) {10.0}
set paths_array(end_clock,7) {square_32s|state_derived_clock[0]:rising}
set paths_array(status_msg,7) {}
set paths_array(index,9) {9}
set paths_array(req_time,4) {10.0}
set paths_array(end_clock,8) {fm_radio|clock:rising}
set paths_array(status_msg,8) {}
set paths_array(s_line,10) {0}
set paths_array(req_time,5) {10.0}
set paths_array(end_clock,9) {fm_radio|clock:rising}
set paths_array(status_msg,9) {}
set paths_array(s_line,11) {0}
set paths_array(req_time,6) {10.0}
set paths_array(s_line,12) {0}
set paths_array(margin_msg,10) {}
set paths_array(req_time,7) {10.0}
set paths_array(s_line,13) {0}
set paths_array(margin_msg,11) {}
set paths_array(req_time,8) {10.0}
set paths_array(s_line,14) {0}
set paths_array(margin_msg,12) {}
set paths_array(req_time,9) {10.0}
set paths_array(s_line,15) {0}
set paths_array(margin_msg,13) {}
set paths_array(s_line,16) {0}
set paths_array(margin_msg,14) {}
set paths_array(end_type,1) {reg}
set paths_array(s_line,17) {0}
set paths_array(margin_msg,15) {}
set paths_array(end_type,2) {reg}
set paths_array(s_line,18) {0}
set paths_array(margin_msg,16) {}
set paths_array(end_type,3) {reg}
set paths_array(margin_msg,17) {}
set paths_array(end_type,4) {reg}
set paths_array(margin_msg,18) {}
set paths_array(end_type,5) {reg}
set paths_array(end_type,6) {reg}
set paths_array(end_type,7) {reg}
set paths_array(end_type,8) {reg}
set paths_array(end_type,9) {reg}
set paths_array(end_type,10) {reg}
set paths_array(end_type,11) {reg}
set paths_array(end_type,12) {reg}
set paths_array(end_type,13) {reg}
set paths_array(end_type,14) {reg}
set paths_array(end_type,15) {reg}
set paths_array(end_type,16) {reg}
set paths_array(slack,10) {5.651}
set paths_array(end_type,17) {reg}
set paths_array(slack,11) {6.086}
set paths_array(start_clk_dly,1) {0.000}
set paths_array(end_type,18) {reg}
set paths_array(slack,12) {6.543}
set paths_array(start_clk_dly,2) {0.000}
set paths_array(slack,13) {8.089}
set paths_array(start_clk_dly,3) {0.000}
set paths_array(slack,14) {9.683}
set paths_array(start_clk_dly,4) {0.000}
set paths_array(slack,15) {9.807}
set paths_array(start_clk_dly,5) {0.000}
set paths_array(slack,16) {18.210}
set paths_array(start_clk_dly,6) {0.000}
set paths_array(slack,17) {18.633}
set paths_array(start_clk_dly,7) {0.000}
set paths_array(slack,18) {18.633}
set paths_array(start_clk_dly,8) {0.000}
set paths_array(start_clk_dly,9) {0.000}
set paths_array(data_delay,10) {0}
set paths_array(end_point,10) {demodulate_inst/qarctan_inst/divider_inst/quotient[28]}
set paths_array(data_delay,11) {0}
set paths_array(end_point,11) {demodulate_inst/qarctan_inst/quad_product[31]}
set paths_array(data_delay,12) {0}
set paths_array(end_point,12) {add_inst/out_din[0]}
set paths_array(data_delay,13) {0}
set paths_array(end_point,13) {demodulate_inst/qarctan_inst/divider_inst/quotient[10]}
set paths_array(data_delay,14) {0}
set paths_array(end_point,14) {square_bp_pilot_fifo_inst/fifo_buf}
set paths_array(data_delay,15) {0}
set paths_array(end_point,15) {left_fifo_inst/fifo_buf}
set paths_array(data_delay,16) {0}
set paths_array(end_point,16) {square_bp_pilot_inst/dout[0]}
set paths_array(data_delay,17) {0}
set paths_array(end_point,17) {left_gain_inst/dout[26]}
set paths_array(start_clk_dly,10) {0.000}
set paths_array(data_delay,18) {0}
set paths_array(end_point,18) {right_gain_inst/dout[26]}
set paths_array(start_clk_dly,11) {0.000}
set paths_array(start_clk_dly,12) {0.000}
set paths_array(start_clk_dly,13) {0.000}
set paths_array(start_clk_dly,14) {0.000}
set paths_array(start_clk_dly,15) {0.000}
set paths_array(start_clk_dly,16) {0.000}
set paths_array(start_clk_dly,17) {0.000}
set paths_array(margin,10) {0}
set paths_array(start_clk_dly,18) {0.000}
set paths_array(margin,11) {0}
set paths_array(start_point,10) {demodulate_inst/qarctan_inst/divider_inst/q_ret}
set paths_array(margin,12) {0}
set paths_array(start_point,11) {demodulate_inst/qarctan_inst/divider_inst/quotient[0]}
set paths_array(margin,13) {0}
set paths_array(start_point,12) {left_fifo_inst/wr_addr[3]}
set paths_array(margin,14) {0}
set paths_array(start_point,13) {demodulate_inst/qarctan_inst/divisor[31]}
set paths_array(margin,15) {0}
set paths_array(start_point,14) {square_bp_pilot_inst/dout[22]}
set paths_array(margin,16) {0}
set paths_array(start_point,15) {add_inst/out_din[0]}
set paths_array(margin,17) {0}
set paths_array(start_point,16) {square_bp_pilot_inst/dout[0]}
set paths_array(margin,18) {0}
set paths_array(start_point,17) {left_gain_inst/dout[26]}
set paths_array(start_point,18) {right_gain_inst/dout[26]}
set synth_array(start_clock,1) {}
set synth_array(start_clock,2) {}
set synth_array(start_clock,3) {}
set synth_array(start_clock,4) {}
set synth_array(start_clock,5) {}
set synth_array(start_clock,6) {}
set synth_array(start_clock,7) {}
set synth_array(start_clock,8) {}
set synth_array(start_clock,9) {}
set synth_array(slack,1) {}
set synth_array(slack,2) {}
set synth_array(slack,3) {}
set synth_array(slack,4) {}
set synth_array(slack,5) {}
set synth_array(slack,6) {}
set synth_array(slack,7) {}
set synth_array(slack,8) {}
set synth_array(slack,9) {}
set synth_array(start_type,1) {}
set synth_array(start_type,2) {}
set synth_array(start_type,3) {}
set synth_array(start_type,4) {}
set synth_array(skew,10) {}
set synth_array(start_type,5) {}
set synth_array(skew,11) {}
set synth_array(start_type,6) {}
set synth_array(skew,12) {}
set synth_array(start_type,7) {}
set synth_array(skew,13) {}
set synth_array(start_type,8) {}
set synth_array(skew,14) {}
set synth_array(start_type,9) {}
set synth_array(skew,15) {}
set synth_array(skew,16) {}
set synth_array(skew,17) {}
set synth_array(skew,18) {}
set synth_array(start_type,10) {}
set synth_array(end_clk_dly,10) {}
set synth_array(start_type,11) {}
set synth_array(end_clk_dly,11) {}
set synth_array(start_type,12) {}
set synth_array(end_clk_dly,12) {}
set synth_array(start_type,13) {}
set synth_array(end_clk_dly,13) {}
set synth_array(start_type,14) {}
set synth_array(end_clk_dly,14) {}
set synth_array(start_type,15) {}
set synth_array(end_clk_dly,15) {}
set synth_array(start_type,16) {}
set synth_array(end_clk_dly,16) {}
set synth_array(start_type,17) {}
set synth_array(end_clk_dly,17) {}
set synth_array(start_type,18) {}
set synth_array(end_clk_dly,18) {}
set synth_array(skew,1) {}
set synth_array(skew,2) {}
set synth_array(skew,3) {}
set synth_array(skew,4) {}
set synth_array(skew,5) {}
set synth_array(skew,6) {}
set synth_array(skew,7) {}
set synth_array(skew,8) {}
set synth_array(skew,9) {}
set synth_array(end_point,1) {}
set synth_array(end_point,2) {}
set synth_array(end_point,3) {}
set synth_array(end_point,4) {}
set synth_array(end_point,5) {}
set synth_array(end_point,6) {}
set synth_array(end_point,7) {}
set synth_array(end_point,8) {}
set synth_array(end_clk_dly,1) {}
set synth_array(end_point,9) {}
set synth_array(end_clk_dly,2) {}
set synth_array(end_clk_dly,3) {}
set synth_array(end_clock,10) {}
set synth_array(end_clk_dly,4) {}
set synth_array(end_clock,11) {}
set synth_array(end_clk_dly,5) {}
set synth_array(end_clock,12) {}
set synth_array(end_clk_dly,6) {}
set synth_array(end_clock,13) {}
set synth_array(end_clk_dly,7) {}
set synth_array(end_clock,14) {}
set synth_array(end_clk_dly,8) {}
set synth_array(end_clock,15) {}
set synth_array(end_clk_dly,9) {}
set synth_array(end_clock,16) {}
set synth_array(end_clock,17) {}
set synth_array(end_clock,18) {}
set synth_array(start_clock,10) {}
set synth_array(start_clock,11) {}
set synth_array(start_clock,12) {}
set synth_array(start_clock,13) {}
set synth_array(start_clock,14) {}
set synth_array(start_clock,15) {}
set synth_array(start_clock,16) {}
set synth_array(start_clock,17) {}
set synth_array(start_clock,18) {}
set synth_array(req_time,10) {}
set synth_array(req_time,11) {}
set synth_array(req_time,12) {}
set synth_array(req_time,13) {}
set synth_array(req_time,14) {}
set synth_array(req_time,15) {}
set synth_array(req_time,16) {}
set synth_array(req_time,17) {}
set synth_array(req_time,18) {}
set synth_array(start_point,1) {}
set synth_array(start_point,2) {}
set synth_array(start_point,3) {}
set synth_array(start_point,4) {}
set synth_array(start_point,5) {}
set synth_array(start_point,6) {}
set synth_array(start_point,7) {}
set synth_array(start_point,8) {}
set synth_array(start_point,9) {}
set synth_array(end_clock,1) {}
set synth_array(end_clock,2) {}
set synth_array(end_clock,3) {}
set synth_array(end_clock,4) {}
set synth_array(end_clock,5) {}
set synth_array(req_time,1) {}
set synth_array(req_time,2) {}
set synth_array(end_clock,6) {}
set synth_array(req_time,3) {}
set synth_array(end_clock,7) {}
set synth_array(req_time,4) {}
set synth_array(end_clock,8) {}
set synth_array(req_time,5) {}
set synth_array(end_clock,9) {}
set synth_array(req_time,6) {}
set synth_array(req_time,7) {}
set synth_array(req_time,8) {}
set synth_array(req_time,9) {}
set synth_array(end_type,1) {}
set synth_array(end_type,2) {}
set synth_array(end_type,3) {}
set synth_array(end_type,4) {}
set synth_array(end_type,5) {}
set synth_array(end_type,6) {}
set synth_array(end_type,7) {}
set synth_array(end_type,8) {}
set synth_array(end_type,9) {}
set synth_array(end_type,10) {}
set synth_array(end_type,11) {}
set synth_array(end_type,12) {}
set synth_array(end_type,13) {}
set synth_array(end_type,14) {}
set synth_array(end_type,15) {}
set synth_array(slack,10) {}
set synth_array(end_type,16) {}
set synth_array(start_clk_dly,1) {}
set synth_array(slack,11) {}
set synth_array(end_type,17) {}
set synth_array(end_type,18) {}
set synth_array(start_clk_dly,2) {}
set synth_array(slack,12) {}
set synth_array(start_clk_dly,3) {}
set synth_array(slack,13) {}
set synth_array(start_clk_dly,4) {}
set synth_array(slack,14) {}
set synth_array(start_clk_dly,5) {}
set synth_array(slack,15) {}
set synth_array(start_clk_dly,6) {}
set synth_array(slack,16) {}
set synth_array(start_clk_dly,7) {}
set synth_array(slack,17) {}
set synth_array(slack,18) {}
set synth_array(start_clk_dly,8) {}
set synth_array(start_clk_dly,9) {}
set synth_array(end_point,10) {}
set synth_array(end_point,11) {}
set synth_array(end_point,12) {}
set synth_array(end_point,13) {}
set synth_array(end_point,14) {}
set synth_array(end_point,15) {}
set synth_array(end_point,16) {}
set synth_array(start_clk_dly,10) {}
set synth_array(end_point,17) {}
set synth_array(start_clk_dly,11) {}
set synth_array(end_point,18) {}
set synth_array(start_clk_dly,12) {}
set synth_array(start_clk_dly,13) {}
set synth_array(start_clk_dly,14) {}
set synth_array(start_clk_dly,15) {}
set synth_array(start_clk_dly,16) {}
set synth_array(start_clk_dly,17) {}
set synth_array(start_clk_dly,18) {}
set synth_array(start_point,10) {}
set synth_array(start_point,11) {}
set synth_array(start_point,12) {}
set synth_array(start_point,13) {}
set synth_array(start_point,14) {}
set synth_array(start_point,15) {}
set synth_array(start_point,16) {}
set synth_array(start_point,17) {}
set synth_array(start_point,18) {}
set sort_list {1 NA 2 NA 3 NA 4 NA 5 NA 6 NA 7 NA 8 NA 9 NA 10 NA 11 NA 12 NA 13 NA 14 NA 15 NA 16 NA 17 NA 18 NA}
set clock_list {}
set foo {ctd_ta_point,right_gain_inst/dout[26]}
set ta_array($foo) {right_gain_inst.dout[26]}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/divider_inst/quotient[28]}
set ta_array($foo) {demodulate_inst.qarctan_inst.divider_inst.quotient[28]}
set foo {ctd_ta_point,left_deemph_inst/state_ret}
set ta_array($foo) {left_deemph_inst.state_ret}
set foo {ctd_ta_point,square_bp_pilot_inst/dout[22]}
set ta_array($foo) {square_bp_pilot_inst.dout[22]}
set foo {ctd_ta_point,left_gain_inst/DEQUANTIZE_27\.i_56_ml_ml_muladd_0[28:0]}
set ta_array($foo) {left_gain_inst.DEQUANTIZE_27\.i_56_ml_ml_muladd_0[28:0]}
set foo {ctd_ta_point,right_gain_inst/in_rd_en_1}
set ta_array($foo) {right_gain_inst.in_rd_en_1}
set foo {ctd_ta_point,fir_cmplx_inst/realshift_reg_CR31}
set ta_array($foo) {fir_cmplx_inst.realshift_reg_CR31}
set foo {ctd_ta_point,square_bp_pilot_fifo_inst/fifo_buf}
set ta_array($foo) {square_bp_pilot_fifo_inst.fifo_buf}
set foo {ctd_ta_point,right_gain_inst/DEQUANTIZE_27\.i_56_ml_ml_muladd_0[28:0]}
set ta_array($foo) {right_gain_inst.DEQUANTIZE_27\.i_56_ml_ml_muladd_0[28:0]}
set foo {ctd_ta_point,left_fifo_inst/fifo_buf}
set ta_array($foo) {left_fifo_inst.fifo_buf}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/divisor[31]}
set ta_array($foo) {demodulate_inst.qarctan_inst.divisor[31]}
set foo {ctd_ta_point,demodulate_inst/qarctan_real[23]}
set ta_array($foo) {demodulate_inst.qarctan_real[23]}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/divider_inst/quotient[10]}
set ta_array($foo) {demodulate_inst.qarctan_inst.divider_inst.quotient[10]}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/divider_inst/q_ret}
set ta_array($foo) {demodulate_inst.qarctan_inst.divider_inst.q_ret}
set foo {ctd_ta_point,demodulate_inst/qarctan_imag[23]}
set ta_array($foo) {demodulate_inst.qarctan_imag[23]}
set foo {ctd_ta_point,mult_demod_lmr_inst/calc_ret_0[0]}
set ta_array($foo) {mult_demod_lmr_inst.calc_ret_0[0]}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/quad_product[31]}
set ta_array($foo) {demodulate_inst.qarctan_inst.quad_product[31]}
set foo {ctd_ta_point,square_bp_pilot_inst/calc_ret_31[0]}
set ta_array($foo) {square_bp_pilot_inst.calc_ret_31[0]}
set foo {ctd_ta_point,mult_demod_lmr_inst/dout[20]}
set ta_array($foo) {mult_demod_lmr_inst.dout[20]}
set foo {ctd_ta_point,add_inst/out_din[0]}
set ta_array($foo) {add_inst.out_din[0]}
set foo {ctd_ta_point,right_deemph_inst/state_ret}
set ta_array($foo) {right_deemph_inst.state_ret}
set foo {ctd_ta_point,left_gain_inst/dout[24]}
set ta_array($foo) {left_gain_inst.dout[24]}
set foo {ctd_ta_point,left_fifo_inst/wr_addr[3]}
set ta_array($foo) {left_fifo_inst.wr_addr[3]}
set foo {ctd_ta_point,fir_cmplx_inst/real_product_ret[28]}
set ta_array($foo) {fir_cmplx_inst.real_product_ret[28]}
set foo {ctd_ta_point,left_gain_inst/dout[26]}
set ta_array($foo) {left_gain_inst.dout[26]}
set foo {ctd_ta_point,square_bp_pilot_inst/dout[0]}
set ta_array($foo) {square_bp_pilot_inst.dout[0]}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/divider_inst/quotient[0]}
set ta_array($foo) {demodulate_inst.qarctan_inst.divider_inst.quotient[0]}
set foo {ctd_ta_point,right_gain_inst/dout[24]}
set ta_array($foo) {right_gain_inst.dout[24]}
set foo {ctd_ta_point,demodulate_inst/qarctan_inst/data_out_temp[24]}
set ta_array($foo) {demodulate_inst.qarctan_inst.data_out_temp[24]}
set foo {ctd_ta_point,left_gain_inst/in_rd_en_1}
set ta_array($foo) {left_gain_inst.in_rd_en_1}
set foo {ctd_ta_point,square_bp_pilot_inst/dout[20]}
set ta_array($foo) {square_bp_pilot_inst.dout[20]}
puts ""
